Add pwr.pkg with sha256 digests
airpwr/airpwr pull request #37
Opened 2022-08-25 19:08 UTC by tbateson

Closes #9

2022-08-27 13:27 UTC, troyaf commented
![image](https://user-images.githubusercontent.com/58236504/187032274-8f867c38-e257-43f4-b044-8d6141c856b9.png)


I think there might be an issue.

2022-08-27 17:58 UTC, tbateson commented
> I think there might be an issue.

Looks like you pressed the enter key a lot? What did you do to cause this? I'm not able to reproduce.

2022-08-27 19:09 UTC, tbateson commented
![image](https://user-images.githubusercontent.com/5900453/187044673-6fa515a2-b5ff-4f00-86c7-41285244e59e.png)

2022-08-28 14:53 UTC, troyaf commented
When there is a `pwr.pkg+pwr.json` in the ancestry of calling a `pwr sh <pkg>`, we crash even if the `pwr.json` is not being used. I don't like that. I would prefer we only do the pkg check specifically when the config was loaded.

2022-08-28 16:34 UTC, troyaf commented
Another case I think we should account for is when there is a PKG file committed and a use hasn't fetched the latest tags yet. We should make sure the version of a package that is loaded is the one in the sum file. If we allow newer versions without complaint but error on old versions, I think we'll get the behavior we want.

We should also account for overrides, and not verify overridden packages.

2022-08-29 00:00 UTC, tbateson commented
> We should make sure the version of a package that is loaded is the one in the sum file. If we allow newer versions without complaint but error on old versions, I think we'll get the behavior we want.

It would probably be better behavior if we forced tags to update when a newer version is encountered in the pkg file, but I'm not sure how easily that could be done.

2022-08-31 02:55 UTC, troyaf commented
Here's an odd scenario that happened:

1. I have `ninja:1.11.0` in the sum file.
1. I changed the config to load `ninja:1.10`, and it crashes as expected.
1. I changed the config to load `ninja:1.10.2`, and the console returns with no output.

2022-08-31 03:01 UTC, troyaf requested changes

2022-08-31 03:01 UTC, troyaf commented on src/pwr.ps1
> +	if (-not $Packages) {
I'm pretty sure this broke overrides

2022-08-31 03:02 UTC, troyaf requested changes
Here's an odd scenario that happened:

1. I have `ninja:1.11.0` in the sum file.
1. I changed the config to load `ninja:1.10`, and it crashes as expected.
1. I changed the config to load `ninja:1.10.2`, and the console returns with no output.

2022-08-31 04:02 UTC, tbateson commented
> Here's an odd scenario that happened

This was caused by a `string`/`SemanticVersion` type mismatch, fixed so that won't ever happen again.

2022-08-31 04:04 UTC, tbateson commented on src/pwr.ps1
> +	if (-not $Packages) {
Oops, forgot override was a switch

2022-08-31 04:32 UTC, tbateson commented on src/pwr.ps1
> +	if (-not $Packages) {
Should be fixed now.

2022-09-01 02:06 UTC, troyaf commented
I'm getting `pwr: package ninja:1.10.2 is older than version 1.11.0 in C:\Users\Troy\code\airpwr\pwr.sum` probably because
`if ($V -and $V.LaterThan($PkgVersion)) {` is not isolated to just `$v.laterthan`.

2022-09-01 18:36 UTC, tbateson commented
> I'm getting `pwr: package ninja:1.10.2 is older than version 1.11.0 in C:\Users\Troy\code\airpwr\pwr.sum` probably because `if ($V -and $V.LaterThan($PkgVersion)) {` is not isolated to just `$v.laterthan`.

So I'm not sure if we're thinking of the same issue, but I've basically made it so that it will only complain about the later-than issue if the pwr.sum is in sync with the pwr.json. Therefore if you have ninja:1.10 in your config it will only check versions that are related to that. E.g. if you have ninja:1.11.1 in pwr.sum it won't crash if you change your pwr.json to ninja:1.10.

2022-12-27 22:04 UTC, closed without merging